name: Github T00ls Auto Sign
 
on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 14 * * *'
jobs:
    build:
        runs-on: ubuntu-latest
 
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'
                architecture: x64
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install requests
            - name: Run
              run: npm install
            - run: python t00ls.py
              env:
                USERNAME: ${{ secrets.USERNAME }}
                PASSWORD ${{ secrets.PASSWORD }}
                QUESTION: ${{ secrets.QUESTION }}
